/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-12-12 04:10:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.util.CmmUtil;
import java.util.Calendar;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/view//local/localSelect.jsp", Long.valueOf(1542353530944L));
    _jspx_dependants.put("/WEB-INF/view/Head.jsp", Long.valueOf(1543902747563L));
    _jspx_dependants.put("/WEB-INF/view/top.jsp", Long.valueOf(1543309041806L));
    _jspx_dependants.put("/WEB-INF/view/bottom.jsp", Long.valueOf(1541637981528L));
    _jspx_dependants.put("/WEB-INF/view//cal/calSelect.jsp", Long.valueOf(1542713585258L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("poly.util.CmmUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String elem = (String)request.getAttribute("elem");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("\tPrologue by HTML5 UP\r\n");
      out.write("\thtml5up.net | @ajlkn\r\n");
      out.write("\tFree for personal and commercial use under the CCA 3.0 license (html5up.net/license)\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("\t\t<!-- head -->\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<head>\r\n");
      out.write("\t\t\t<title>main</title>\r\n");
      out.write("\t\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/assets/css/main.css\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \t<!-- 부트스트랩 -->\r\n");
      out.write("\t\t\t<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\t\t\t<!-- 부가적인 테마 -->\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\t\t\t<!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->\r\n");
      out.write("\t\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\">\r\n");
      out.write("\t\t\t<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("\t\t\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\t<!-- 부트스트랩 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				String userSeq = CmmUtil.nvl((String)session.getAttribute("userSeq"));
				String email = CmmUtil.nvl((String)session.getAttribute("email"));
				String name = CmmUtil.nvl((String)session.getAttribute("name"));
				String hp = CmmUtil.nvl((String)session.getAttribute("hp"));
				String birth = CmmUtil.nvl((String)session.getAttribute("birth"));
				String gender = CmmUtil.nvl((String)session.getAttribute("gender"));
			
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t.Con_ST {\r\n");
      out.write("\t\t    position: relative;\r\n");
      out.write("\t\t    display: block;\r\n");
      out.write("\t\t    width: 100%;\r\n");
      out.write("\t\t    height: 328px;\r\n");
      out.write("\t\t    overflow: hidden;\r\n");
      out.write("\t\t    background: url(http://ticketimage.interpark.com/TicketImage/main/100506_sub/bg_t_play.jpg) top left no-repeat;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.Con_ST .wrap_Tview {\r\n");
      out.write("\t\t    position: relative;\r\n");
      out.write("\t\t    width: 900px;\r\n");
      out.write("\t\t    margin-top: 44px;\r\n");
      out.write("\t\t    margin-left: 56px;\r\n");
      out.write("\t\t    display: block;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdl.Tview {\r\n");
      out.write("\t\t    position: relative;\r\n");
      out.write("\t\t    float: left;\r\n");
      out.write("\t\t    width: 129px;\r\n");
      out.write("\t\t    margin: 0 6px;\r\n");
      out.write("\t\t    display: inline;\r\n");
      out.write("\t\t    overflow: hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdl.Tview dt.Tposter {\r\n");
      out.write("\t\t    position: relative;\r\n");
      out.write("\t\t    width: 129px;\r\n");
      out.write("\t\t    height: 161px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdl.Tview dt.Tposter a {\r\n");
      out.write("\t\t    width: 129px;\r\n");
      out.write("\t\t    height: 161px;\r\n");
      out.write("\t\t    display: inline-block;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdl.Tview dt.Tposter .info {\r\n");
      out.write("\t\t    position: absolute;\r\n");
      out.write("\t\t    z-index: 10;\r\n");
      out.write("\t\t    top: 118px;\r\n");
      out.write("\t\t    left: 3px;\r\n");
      out.write("\t\t    width: 123px;\r\n");
      out.write("\t\t    height: 35px;\r\n");
      out.write("\t\t    background: url(http://ticketimage.interpark.com/TicketImage/main/100506_sub/tp_bg_info.png);\r\n");
      out.write("\t\t    cursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdl.Tview dt.Tposter .info .txt1 {\r\n");
      out.write("\t\t    display: block;\r\n");
      out.write("\t\t    color: #e7e7e7;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t\t    font-size: 11px;\r\n");
      out.write("\t\t    margin-top: 5px;\r\n");
      out.write("\t\t    height: 13px;\r\n");
      out.write("\t\t    overflow: hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdl.Tview dt.Tposter .info .txt2 {\r\n");
      out.write("\t\t    display: block;\r\n");
      out.write("\t\t    color: #ffcfce;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t\t    font-size: 11px;\r\n");
      out.write("\t\t    margin-top: 0;\r\n");
      out.write("\t\t    height: 14px;\r\n");
      out.write("\t\t    overflow: hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdl.Tview dd {\r\n");
      out.write("\t\t    position: relative;\r\n");
      out.write("\t\t    color: #fff;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t\t    font-size: 11px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdl.Tview dd span.txt1 {\r\n");
      out.write("\t\t    display: block;\r\n");
      out.write("\t\t    width: 129px;\r\n");
      out.write("\t\t    height: 14px;\r\n");
      out.write("\t\t    color: #FFF;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t\t    font-size: 12px;\r\n");
      out.write("\t\t    font-weight: bold;\r\n");
      out.write("\t\t    letter-spacing: -0.1em;\r\n");
      out.write("\t\t    overflow: hidden;\r\n");
      out.write("\t\t    margin-top: 7px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdl.Tview dd span.txt2 {\r\n");
      out.write("\t\t    display: block;\r\n");
      out.write("\t\t    color: #a0a0a0;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t\t    font-size: 11px;\r\n");
      out.write("\t\t    margin-top: 3px;\r\n");
      out.write("\t\t    letter-spacing: -0.1em;\r\n");
      out.write("\t\t    height: 12px;\r\n");
      out.write("\t\t    overflow: hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdl.Tview dd span.txt3 {\r\n");
      out.write("\t\t    display: block;\r\n");
      out.write("\t\t    color: #a0a0a0;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t\t    font-size: 11px;\r\n");
      out.write("\t\t    font-family: arial;\r\n");
      out.write("\t\t    letter-spacing: 0;\r\n");
      out.write("\t\t    height: 11px;\r\n");
      out.write("\t\t    overflow: hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t</head>\r\n");
      out.write("\t\t<!-- head -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- top -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t\t<!-- Header -->\r\n");
      out.write("\t\t\t<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"top\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"logo\" onclick=\"location.href='/main.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"image avatar48\"><img src=\"/assets/images/avatar.jpg\" alt=\"\" /></span>\r\n");
      out.write("\t\t\t\t\t\t\t<h1 id=\"title\">LOGO</h1>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Hyperspace Engineer</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Nav -->\r\n");
      out.write("\t\t\t\t\t\t<nav id=\"nav\" style=\"position:relative;\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if(session.getAttribute("userSeq") != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>");
      out.print(session.getAttribute("name") );
      out.write("님 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" onclick=\"location.href='/user/Logout.do'\">로그아웃</button></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"\" id=\"contact-link\"><span class=\"icon fa-envelope\">로그인</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 로그인 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; top:0px;\" onclick=\"location.href='/user/userLogin.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\"><a href=\"#top\" id=\"top-link\"><span class=\"icon fa-home\">지역/날짜별 검색</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\"><a href=\"\" id=\"portfolio-link\"><span class=\"icon fa-th\">자막제공</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\"><a href=\"#about\" id=\"about-link\"><span class=\"icon fa-user\">공연장</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\"><a href=\"\" id=\"contact-link\"><span class=\"icon fa-user\">게시판</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\"><a href=\"\" id=\"contact-link\"><span class=\"icon fa-user\">회원목록</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 지역/날짜 별 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; bottom:200px;\" onclick=\"location.href='/main.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 자막제공 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; bottom:150px;\" onclick=\"location.href='/speech/speechGetText.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 공연장 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; bottom:100px;\" onclick=\"location.href='/theater/theaterSelect.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 게시판 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; bottom:50px;\" onclick=\"location.href='/notice/noticeList.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 회원목록 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; bottom:0px;\" onclick=\"location.href='/user/userList.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"bottom\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Social Icons -->\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"icons\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-facebook\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-github\"><span class=\"label\">Github</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-dribbble\"><span class=\"label\">Dribbble</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-envelope\"><span class=\"label\">Email</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <!-- Scripts -->\r\n");
      out.write("\t\t\t<script src=\"/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/browser.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/main.js\"></script> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<!-- top -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Main -->\r\n");
      out.write("\t\t\t<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Intro -->\r\n");
      out.write("\t\t\t\t\t<section id=\"top\" class=\"one dark cover\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"Con_ST\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(elem );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Portfolio -->\r\n");
      out.write("\t\t\t\t\t<section id=\"portfolio\" class=\"two\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>지역별  / 날짜별 검색</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<img src=\"/assets/images/locMap.gif\" usemap=\"#LeftAreaMap\">\r\n");
      out.write("\t<map name=\"LeftAreaMap\" id=\"LeftAreaMap\">\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"97,112,117,121\" href=\"/local/localSelect.do?sidoCode=11\"><!-- 서울11 o-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"171,100,246,144\" href=\"/local/localSelect.do?sidoCode=42\"><!-- 강원 42-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"58,101,83,118\" href=\"/local/localSelect.do?sidoCode=28\"><!-- 인천 28-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"98,135,139,152\" href=\"/local/localSelect.do?sidoCode=41\"><!-- 경기 41 o-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"134,171,181,191\" href=\"/local/localSelect.do?sidoCode=43\"><!-- 충북 43 -->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"70,187,117,203\" href=\"/local/localSelect.do?sidoCode=44\"><!-- 충남 44-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"121,209,145,226\" href=\"/local/localSelect.do?sidoCode=30\"><!-- 대전30 o-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"194,183,255,210\" href=\"/local/localSelect.do?sidoCode=47\"><!-- 경북 47-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"196,246,221,265\" href=\"/local/localSelect.do?sidoCode=27\"><!-- 대구 27 o-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"243,270,269,288\" href=\"/local/localSelect.do?sidoCode=31\"><!-- 울산 31 -->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"224,296,253,320\" href=\"/local/localSelect.do?sidoCode=26\"><!-- 부산 26 o-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"163,286,209,305\" href=\"/local/localSelect.do?sidoCode=48\"><!-- 경남 48 o 창원 -->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"93,260,144,283\" href=\"/local/localSelect.do?sidoCode=45\"><!-- 전북 45 o 전주-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"83,303,108,320\" href=\"/local/localSelect.do?sidoCode=29\"><!-- 광주 29 o -->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"54,335,110,370\" href=\"/local/localSelect.do?sidoCode=46\"><!-- 전남 46-->\r\n");
      out.write("\t\t<area name=\"rect\" coords=\"55,410,101,427\" href=\"/local/localSelect.do?sidoCode=50\"><!-- 제주 50 o -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t</map>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/assets/css/calStyle.css\"/>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/assets/js/calendar.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"jquery-calendar\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction day(){\r\n");
      out.write("\t\tvar year = $('table.cal>caption').find('span.month').text();\r\n");
      out.write("\t\tvar day = $('table.cal>tbody>tr').find('td.active').text();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(day < 10){\r\n");
      out.write("\t\t\tday = '0' + day;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tyear = year.replace(\"-\",\"\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar stdate = year + day ;\r\n");
      out.write("//\t\talert(\"stdate() : \" + stdate);\r\n");
      out.write("\t\tlocation.href=\"/cal/calSelect.do?stdate=\" +stdate;\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- About Me -->\r\n");
      out.write("\t\t\t\t\t<!-- <section id=\"about\" class=\"three\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>홍보 배너</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</section> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Contact -->\r\n");
      out.write("\t\t\t\t\t<section id=\"contact\" class=\"four\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>유의사항</h2>\r\n");
      out.write("\t\t\t\t\t\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p>취소 시 예매수수료는 예매 당일 밤 12시 이전까지 환불되며, 그 이후 기간에는 환불되지 않습니다.\r\n");
      out.write("웹 취소가능시간 이후에는 취소가 불가합니다.\r\n");
      out.write(" 단, 관람일 당일 취소가능 한 상품의 경우 관람일 당일 취소 시에는 티켓금액의 90%가 과금됩니다.\r\n");
      out.write("상품의 특성에 따라서, 취소수수료 정책이 달라질 수 있습니다.(각 상품 예매 시 취소수수료 확인)\r\n");
      out.write("배송 및 반송처리 된 티켓의 배송료는 환불되지 않습니다.\r\n");
      out.write("금주 주말 (토/일)공연 취소를 원할 경우 내사수령 바랍니다. 우편으로 보낼 시 우체국이 토요일 근무를 안하는 관계로 수취인(인터파크)수령이 불가능하여 취소처리가 되지 않을 수 있습니다.\r\n");
      out.write("취소는 관람일 하루 전(평일/주말/공휴일 오후 5시, 토요일 오전 11시 이전)까지 직접 취소가 가능하며, 배송이 시작된 티켓의 경우 티켓이 인터파크 티켓 고객센터로 공연 전일까지 반송되어야 취소가능하며, 취소수수료는 도착일자 기준으로 부과됩니다.\r\n");
      out.write("(※ 단, 배송료는 환불되지 않으며 일괄배송 상품의 경우 취소에 대한 자세한 문의는 고객센터로 문의해주시기 바랍니다.)\r\n");
      out.write("(공연 전일이 휴일인 경우, 휴일 전날까지) 반송이 확인되지 않은 티켓은 현장에서도 수령하실 수 없으며, 공연 관람 및 환불이 불가합니다.          \r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"background-color:#cccccc; width:100%;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t공연 당일 현장 교부처에서 예약번호 및 본인 확인 후 티켓을 수령하실 수 있습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t상단 예매확인/취소 메뉴에서 예매내역을 프린트하여 가시면 편리합니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- bottom -->\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \t <!-- Footer -->\r\n");
      out.write("\t\t\t<div id=\"footer\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Copyright -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href=\"http://html5up.net\">HTML5 UP</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
