/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-12-12 04:34:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.util.RestoreScript;
import poly.dto.NoticeDTO;
import java.util.ArrayList;
import poly.dto.UserDTO;
import java.util.List;
import poly.util.CmmUtil;

public final class noticeDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/view/Head.jsp", Long.valueOf(1543902747563L));
    _jspx_dependants.put("/WEB-INF/view/top.jsp", Long.valueOf(1543309041806L));
    _jspx_dependants.put("/WEB-INF/view/bottom.jsp", Long.valueOf(1541637981528L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("poly.dto.UserDTO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("poly.util.RestoreScript");
    _jspx_imports_classes.add("poly.util.CmmUtil");
    _jspx_imports_classes.add("poly.dto.NoticeDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

	NoticeDTO nDTO = (NoticeDTO)request.getAttribute("nDTO");


	//게시판 조회 결과 보여주기
	if (nDTO==null){
		nDTO = new NoticeDTO();
	}
	List<NoticeDTO> rList = (List<NoticeDTO>)request.getAttribute("rList");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t\t<!-- head -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<head>\r\n");
      out.write("\t\t\t<title>main</title>\r\n");
      out.write("\t\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/assets/css/main.css\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \t<!-- 부트스트랩 -->\r\n");
      out.write("\t\t\t<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\t\t\t<!-- 부가적인 테마 -->\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\t\t\t<!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->\r\n");
      out.write("\t\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\">\r\n");
      out.write("\t\t\t<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("\t\t\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\t<!-- 부트스트랩 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				String userSeq = CmmUtil.nvl((String)session.getAttribute("userSeq"));
				String email = CmmUtil.nvl((String)session.getAttribute("email"));
				String name = CmmUtil.nvl((String)session.getAttribute("name"));
				String hp = CmmUtil.nvl((String)session.getAttribute("hp"));
				String birth = CmmUtil.nvl((String)session.getAttribute("birth"));
				String gender = CmmUtil.nvl((String)session.getAttribute("gender"));
			
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\t<style>\r\n");
      out.write("\t\t\t@-moz-document url-prefix() {\r\n");
      out.write("\t \t\t fieldset { display: table-cell; }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t</style>\r\n");
      out.write("\t\t\t<!-- 부트스트랩 -->\r\n");
      out.write("\t\t\t\t<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\t\t\t\t<!-- 부가적인 테마 -->\r\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\t\t\t\t<!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->\r\n");
      out.write("\t\t\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t\t<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("\t\t\t\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\t<!-- 부트스트랩 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t//댓글 수정 삭제 버튼\r\n");
      out.write("\t\t\tfunction reClick(r,u){\r\n");
      out.write("\t\t\t\t//r : reSeq \r\n");
      out.write("\t\t\t\t//u: userSeq\r\n");
      out.write("\t\t\t\t//(String)session.getAttribute(\"userSeq\")\r\n");
      out.write("\t\t\t \tvar ss_userSeq = ");
      out.print((String)session.getAttribute("userSeq"));
      out.write(";\r\n");
      out.write("\t\t\t\tvar upWrite = \"#upWrite\"+r+\"\";\r\n");
      out.write("\t\t\t\talert(upWrite);\r\n");
      out.write("\t\t\t \tif(ss_userSeq == u){\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\talert(\"수정 삭제\");\r\n");
      out.write("\t\t\t\t\tvar upBtn=\"\";\r\n");
      out.write("\t\t\t\t\t\t//upBtn= \"<button class='btn btn-default pull-right' onclick='#'>test</button>\"\r\n");
      out.write("\t\t\t\t\t\tupBtn += \"<div class='btn-group pull-right' role='group' align='right' id='\"+upWrite+\"'>\";\r\n");
      out.write("\t\t\t\t\t\tupBtn +=\"<button type='button' class='btn btn-default' onClick='JavaScript:upBtn(\"+r+\")'>수정</button>\";\r\n");
      out.write("\t\t\t\t\t\tupBtn +=\"<button type='button' class='btn btn-default' onClick='JavaScript:delBtn(\"+r+\")'>삭제</button>\";\r\n");
      out.write("\t\t\t\t\t\tupBtn +=\"</div>\"\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(upWrite).html(upBtn);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"작성자만 수정 가능합니다.\");\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//댓글 수정  뷰\r\n");
      out.write("\t\t\tfunction upBtn(r){\r\n");
      out.write("\t\t\t\tvar upView = \"#upView\"+r+\"\";\r\n");
      out.write("\t\t\t\t//alert(upView);\r\n");
      out.write("\t\t\t\t//alert(r);\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/notice/upReple.do\",\r\n");
      out.write("\t\t\t\t\tmethod :\"post\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\"repleSeq\" : r\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\tvar upBtnView =\"\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"<div style='margin-bottm:10%;'>\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"<form id='ajaxfromUp' method='post' action='/seller/board/updateRe.do'>\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"<textarea rows='3' class='col-sm-12 form-control' id='reContentUp' name='reContentUp' maxlength='2048'></textarea>\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"<input type='hidden' name='regDateUp'/>\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"<input type='hidden' name='userSeqUp' value='\"+data.userSeq+\"'/>\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"<input type='hidden' name='boardPSeqUp' value='\"+data.boardPSeq+\"'/>\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"<input type='hidden' name='levelUp' value='1'/>\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"<input type='hidden' name='repleSeq' value='\"+r+\"'/>\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"</form>\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"<button class='btn btn-default pull-right' onclick='JavaScript:updateRe()'>등록</button>\";\r\n");
      out.write("\t\t\t\t\t\t\tupBtnView += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(upView).html(upBtnView);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(upBtnView);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</head>\r\n");
      out.write("\t\t<!-- head -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- top -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t\t<!-- Header -->\r\n");
      out.write("\t\t\t<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"top\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"logo\" onclick=\"location.href='/main.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"image avatar48\"><img src=\"/assets/images/avatar.jpg\" alt=\"\" /></span>\r\n");
      out.write("\t\t\t\t\t\t\t<h1 id=\"title\">LOGO</h1>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Hyperspace Engineer</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Nav -->\r\n");
      out.write("\t\t\t\t\t\t<nav id=\"nav\" style=\"position:relative;\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if(session.getAttribute("userSeq") != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>");
      out.print(session.getAttribute("name") );
      out.write("님 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" onclick=\"location.href='/user/Logout.do'\">로그아웃</button></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"\" id=\"contact-link\"><span class=\"icon fa-envelope\">로그인</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 로그인 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; top:0px;\" onclick=\"location.href='/user/userLogin.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\"><a href=\"#top\" id=\"top-link\"><span class=\"icon fa-home\">지역/날짜별 검색</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\"><a href=\"\" id=\"portfolio-link\"><span class=\"icon fa-th\">자막제공</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\"><a href=\"#about\" id=\"about-link\"><span class=\"icon fa-user\">공연장</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\"><a href=\"\" id=\"contact-link\"><span class=\"icon fa-user\">게시판</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height:50px;\"><a href=\"\" id=\"contact-link\"><span class=\"icon fa-user\">회원목록</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 지역/날짜 별 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; bottom:200px;\" onclick=\"location.href='/main.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 자막제공 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; bottom:150px;\" onclick=\"location.href='/speech/speechGetText.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 공연장 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; bottom:100px;\" onclick=\"location.href='/theater/theaterSelect.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 게시판 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; bottom:50px;\" onclick=\"location.href='/notice/noticeList.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 회원목록 클릭  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%; cursor:pointer; border:1px solid #cccccc; background-color:rgba(255,255,255,0); position:absolute; height:50px; bottom:0px;\" onclick=\"location.href='/user/userList.do'\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"bottom\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Social Icons -->\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"icons\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-facebook\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-github\"><span class=\"label\">Github</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-dribbble\"><span class=\"label\">Dribbble</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-envelope\"><span class=\"label\">Email</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <!-- Scripts -->\r\n");
      out.write("\t\t\t<script src=\"/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/browser.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/assets/js/main.js\"></script> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t$(document).ready( function () {\r\n");
      out.write("\t\t    $('#DT').DataTable();\r\n");
      out.write("\t\t} );\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- ajax form  -->\r\n");
      out.write("\t\t<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js\"></script> \r\n");
      out.write("\t\t<script src=\"http://malsup.github.com/jquery.form.js\"></script> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style=\"height:7%; background-color:#4e4945;\">&nbsp;&nbsp;&nbsp;</div>\r\n");
      out.write("\t\t<!-- top -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- main -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h3>게시글 상세</h3>\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t \t<table class=\"table\">\r\n");
      out.write("\t\t\t \t<tbody>\r\n");
      out.write("\t\t \t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t<td>번호 : ");
      out.print(nDTO.getNoticeSeq());
      out.write("</td>\r\n");
      out.write("\t\t \t\t\t\t<td>제목 : ");
      out.print(RestoreScript.doRestore(nDTO.getTitle()));
      out.write("</td>\r\n");
      out.write("\t\t \t\t\t\t<td>조회수 : ");
      out.print(nDTO.getCnt());
      out.write("</td>\r\n");
      out.write("\t\t \t\t\t</tr>\r\n");
      out.write("\t\t \t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t \t\t\t\t<td colspan=\"3\">내용 : ");
      out.print(RestoreScript.doRestore(nDTO.getContent()));
      out.write("</td>\r\n");
      out.write("\t\t \t\t\t</tr>\r\n");
      out.write("\t\t \t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t<td></td>\r\n");
      out.write("\t\t \t\t\t\t<td>작성일 : ");
      out.print(nDTO.getUpdDate());
      out.write("</td>\r\n");
      out.write("\t\t \t\t\t\t<td>작성자 : ");
      out.print(nDTO.getUpdNo());
      out.write("</td>\r\n");
      out.write("\t\t \t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t \t\t\r\n");
      out.write("\t\t\t \t</tbody>\r\n");
      out.write("\t\t\t </table>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div align=\"right\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-default\" onclick=\"location.href='#'\">목록</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-default\" onclick=\"location.href='/notice/noticeUpdateView.do?noticeSeq=");
      out.print(nDTO.getNoticeSeq());
      out.write("'\">수정</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-default\" onclick=\"location.href='/notice/noticeDelete.do?noticeSeq=");
      out.print(nDTO.getNoticeSeq());
      out.write("'\">삭제</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" action=\"/notice/reNoticeReg.do\" id=\"ajaxForm\">\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"review\" class=\"col-sm-2 control-label\">review</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t<textarea rows=\"3\" class=\"col-sm-12 form-control\" name=\"reNotice\" id=\"reNotice\"></textarea>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t      <button type=\"button\" class=\"btn btn-default\" onclick=\"JavaScript:reReg()\">등록</button>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t  <input type=\"hidden\" name=\"userSeq\" value=\"");
      out.print(userSeq);
      out.write("\"/>\r\n");
      out.write("\t\t\t\t  <input type=\"hidden\" name=\"noticeSeq\" value=\"");
      out.print(nDTO.getNoticeSeq());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"rList\">\r\n");
      out.write("\t\t\t\t");
if(rList.size() >0 ){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr><th></th></tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
 for (int i=0; i < rList.size(); i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\tuserSeq : ");
      out.print( rList.get(i).getUserSeq() );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(rList.get(i).getUpdDate());
      out.write("<br/>\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent : ");
      out.print( rList.get(i).getReNotice() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id='upWrite\"");
      out.print(rList.get(i).getReNoticeSeq() );
      out.write("\"'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-default pull-right\" onclick=\"javascript:reClick('");
      out.print(rList.get(i).getReNoticeSeq() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(rList.get(i).getUpdNo() );
      out.write("')\">...</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
 }
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t<!--main -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- bottom -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \t <!-- Footer -->\r\n");
      out.write("\t\t\t<div id=\"footer\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Copyright -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href=\"http://html5up.net\">HTML5 UP</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>");
      out.write("\r\n");
      out.write("\t\t<!-- bottom -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tfunction reReg(){\r\n");
      out.write("\t\t\t\talert(\"댓글 등록 완료\");\r\n");
      out.write("\t\t\t\t$('#ajaxForm').ajaxForm({\r\n");
      out.write("\t\t\t\t\tbeforeSubmit : function(){\r\n");
      out.write("\t\t\t\t\t\tif($('#reNotice').val() == \"\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"내용을 입력해주세요\");\r\n");
      out.write("\t\t\t\t\t\t\t$('#reNotice').focus();\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\tvar content = \"\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent += \"<table id='DT'>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent += \"<thead>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent += \"<tr><th></th></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent += \"</thead>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent += \"<tbody>\";\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$.each(data,function(key,value){\r\n");
      out.write("\t\t\t\t\t\t\tcontent +=\"<tr>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent +=\"<td>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent +=\"userSeq : \" + value.updNo +\" \" + value.updDate + \"<br/>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent +=\"content : \" + value.reNotice;\r\n");
      out.write("\t\t\t\t\t\t\tcontent +=\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent +=\"<td>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent +=\"<div id='upWrite\"+value.reNoticeSeq+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent +='<button class=\"btn btn-default pull-right\" onclick=\"javascript:reClick(&#39;'+value.reNoticeSeq+'&#39;,'+value.updNo+')\">...</button>'\r\n");
      out.write("\t\t\t\t\t\t\tcontent +=\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tcontent +=\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t$('#rList').html(content); \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror:function(){\r\n");
      out.write("\t\t\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}).submit();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
